### ISSUE TITLE
Cmds

### ISSUE THREAD

**Issue by BeefaroniSalesman** [pkuba208/Automatic-torrent-sideloader#1]
Just... where exactly do I put these cmds (sorry if this is a dumb question, I'm migrating from a different loader)

**Comment by pkuba208** [comment]
first of all: you need to downoad the windows version. It has a separate branch https://github.com/pkuba208/Automatic-torrent-sideloader/tree/windows
Then open the folder with the downloaded script, right click and press open in terminal
once the terminal is opened type in cmd.
Once you've donne that, type in setup.bat and after that, torrenter.sh

**Comment by pkuba208** [comment]
Also if you want faster help,chat with me on Reddit.
https://s.reddit.com/c/1a5jnxst2lwmt?utm_medium=android_app&utm_source=share

**Comment by pkuba208** [comment]
User error, closing issue
